# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Fill in the Blanks', 'Fill in the Blanks'), ('Short Answer', 'Short Answer'), ('Free Response', 'Free Response'), ('Code Response', 'Code'), ('True/False', 'True/False'), ('Matching', 'Matching'), ('Fill in the Table', 'Fill in the Table')], default='Short Answer', max_length=50, verbose_name='question type')),
                ('released', models.BooleanField(default=False)),
                ('authorship_year', models.IntegerField()),
                ('original_exam', models.CharField(blank=True, max_length=50)),
                ('original_question', models.IntegerField(blank=True)),
                ('points', models.IntegerField(blank=True)),
                ('difficulty', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='quizbank.Tag'),
        ),
    ]
