# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
