# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0002_auto_20160627_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
