# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0003_auto_20160627_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
