# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0004_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='quizbank/no-img.jpg', upload_to='quizbank/'),
        ),
    ]
