# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0006_auto_20160627_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='quizbank/no-img.jpg', upload_to='quizbank/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quizbank.Tag'),
        ),
    ]
