# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0008_auto_20160627_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='authorship_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='quizbank/no-img.jpg', upload_to='quizbank/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='original_exam',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='original_question',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(blank=True, choices=[('Multiple Choice', 'Multiple Choice'), ('Fill in the Blanks', 'Fill in the Blanks'), ('Short Answer', 'Short Answer'), ('Free Response', 'Free Response'), ('Code Response', 'Code'), ('True/False', 'True/False'), ('Matching', 'Matching'), ('Fill in the Table', 'Fill in the Table')], default='Short Answer', max_length=50, verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quizbank.Tag'),
        ),
    ]
