# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0010_auto_20160627_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Fill in the Blanks', 'Fill in the Blanks'), ('Short Answer', 'Short Answer'), ('Free Response', 'Free Response'), ('Code Response', 'Code'), ('True/False', 'True/False'), ('Matching', 'Matching'), ('Fill in the Table', 'Fill in the Table')], default='Short Answer', max_length=50, verbose_name='question type'),
        ),
    ]
