# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0011_auto_20160627_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='a_image',
            field=models.ImageField(blank=True, null=True, upload_to='quizbank/a/'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_image',
            field=models.ImageField(blank=True, null=True, upload_to='quizbank/q/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default='', help_text='Syntax Guide: *underline*, **bold**, $LaTeX$, [[image]]', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, help_text='1 is least difficult, 5 is most difficult', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='original_exam',
            field=models.CharField(blank=True, help_text='e.g. 2015 Quiz 0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, default='', help_text='Syntax Guide: *underline*, **bold**, $LaTeX$, [[image]]', null=True),
        ),
    ]
