# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0013_auto_20160627_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default='', help_text='Syntax Guide: *underline*, **bold**, $LaTeX$, [[image]], `inline code`, ```code block```', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, default='', help_text='Syntax Guide: *underline*, **bold**, $LaTeX$, [[image]], `inline code`, ```code block```', null=True),
        ),
    ]
