# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0014_auto_20160628_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Fill in the Blanks', 'Fill in the Blanks'), ('Short Answer', 'Short Answer'), ('Free Response', 'Free Response'), ('Code Response', 'Code Response'), ('True/False', 'True/False'), ('Matching', 'Matching'), ('Fill in the Table', 'Fill in the Table'), ('Other', 'Other')], default='Short Answer', max_length=50, verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='released',
            field=models.BooleanField(default=False, verbose_name='Available to Public'),
        ),
    ]
