# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_userprofile_school_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acct_type',
            field=models.CharField(choices=[('DEV', 'Developer'), ('ADM', 'Admin'), ('CNT', 'Content'), ('TCH', 'Teacher')], default='TCH', max_length=3),
        ),
    ]
