# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20160625_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='duration',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='module',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
