# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20160625_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='num',
            field=models.IntegerField(unique=True, verbose_name='chapter number'),
        ),
        migrations.AlterField(
            model_name='module',
            name='num',
            field=models.IntegerField(verbose_name='module number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_proof',
            field=models.CharField(blank=True, max_length=500, verbose_name='proof of status'),
        ),
    ]
