# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20160625_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
