# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_userprofile_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='acct_type',
            field=models.CharField(choices=[('ADM', 'Admin'), ('CNT', 'Content'), ('TCH', 'Teacher')], default='TCH', max_length=3),
        ),
    ]
