# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_auto_20160627_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('column', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.ResourceType'),
        ),
    ]
