# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_auto_20160629_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.ResourceType', verbose_name='resource type'),
        ),
    ]
