# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_auto_20160705_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
    ]
