# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bgcolor',
            field=models.CharField(default='F0F3F6', max_length=7),
        ),
    ]
