# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_userprofile_bgcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='headercolor',
            field=models.CharField(default='D7DDE4', max_length=7),
        ),
    ]
