# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_userprofile_headercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sidecolor',
            field=models.CharField(default='3A4651', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='textcolor',
            field=models.CharField(default='4F5F6F', max_length=7),
        ),
    ]
