# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_auto_20160714_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('contents', models.TextField(default='')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
