# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
