# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_page_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_public',
            field=models.BooleanField(default=False),
        ),
    ]
