# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_auto_20160715_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.CharField(default='', max_length=300),
        ),
    ]
