# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_auto_20160721_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='duration',
        ),
    ]
