# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_remove_module_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
